function v5_validate_window_summary_against_long(window_summary, channel_long, lzc_long)

for k = 1:height(window_summary)

    row = window_summary(k,:);

    ch_subset = channel_long( ...
        channel_long.Participant == row.Participant & ...
        channel_long.Session == row.Session & ...
        channel_long.Eyes == row.Eyes & ...
        channel_long.Epoch == row.Epoch & ...
        channel_long.File == row.File & ...
        channel_long.WindowSec == row.WindowSec & ...
        channel_long.Window == row.Window, :);

    lzc_subset = lzc_long( ...
        lzc_long.Participant == row.Participant & ...
        lzc_long.Session == row.Session & ...
        lzc_long.Eyes == row.Eyes & ...
        lzc_long.Epoch == row.Epoch & ...
        lzc_long.File == row.File & ...
        lzc_long.WindowSec == row.WindowSec & ...
        lzc_long.Window == row.Window, :);

    if height(lzc_subset) ~= 1
        error('Window summary validation failed: expected exactly one LZc row.');
    end

    assert_close(double(row.Mean_LZs), mean(asnum(ch_subset.LZs), 'omitnan'), 'Mean_LZs mismatch');
    assert_close(double(row.Mean_LZsN), mean(asnum(ch_subset.LZsN), 'omitnan'), 'Mean_LZsN mismatch');
    assert_close(double(row.LZc), double(lzc_subset.LZc(1)), 'LZc mismatch');
    assert_close(double(row.LZcN), double(lzc_subset.LZcN(1)), 'LZcN mismatch');
    assert_close(double(row.RawLZc), double(lzc_subset.RawLZc(1)), 'RawLZc mismatch');
    assert_close(double(row.PhaseRawLZcMean), double(lzc_subset.PhaseRawLZcMean(1)), 'PhaseRawLZcMean mismatch');

end

end

function assert_close(a, b, msg)
tol = 1e-10;
if abs(a - b) > tol
    error('%s. %.15g vs %.15g', msg, a, b);
end
end
