function temporal_pair_index = temporal_eo_minus_ec_pair_differences( ...
    all_results, output_root, temporal_plot_lzc_column, diff_color_limits, temporal_diff_dir)

all_results = normalize_lzc_table_ids(all_results);

file_rows = unique(all_results(:, {'Participant','Session','Eyes','Epoch','File'}), 'rows');
pair_keys = unique(file_rows(:, {'Participant','Session','Epoch'}), 'rows');

temporal_pair_index = table();

for k = 1:height(pair_keys)

    participant = normalize_participant_id(pair_keys.Participant(k));
    session_name = string(pair_keys.Session(k));
    epoch_name = string(pair_keys.Epoch(k));

    eo_row = file_rows( ...
        file_rows.Participant == participant & ...
        file_rows.Session == session_name & ...
        file_rows.Epoch == epoch_name & ...
        file_rows.Eyes == "EO", :);

    ec_row = file_rows( ...
        file_rows.Participant == participant & ...
        file_rows.Session == session_name & ...
        file_rows.Epoch == epoch_name & ...
        file_rows.Eyes == "EC", :);

    if isempty(eo_row) || isempty(ec_row)
        continue;
    end

    eo_row = eo_row(1,:);
    ec_row = ec_row(1,:);

    participant_dir = fullfile(output_root, char(participant));
    temporal_dir = fullfile(participant_dir, 'Temporal_LZc');

    eo_file_tag = sprintf('%s_%s_%s_%s_%s', ...
        char(participant), char(eo_row.Session), char(eo_row.Eyes), char(eo_row.Epoch), char(eo_row.File));

    ec_file_tag = sprintf('%s_%s_%s_%s_%s', ...
        char(participant), char(ec_row.Session), char(ec_row.Eyes), char(ec_row.Epoch), char(ec_row.File));

    eo_mat = fullfile(temporal_dir, ...
        [eo_file_tag '_' char(temporal_plot_lzc_column) '_temporal_LZc.mat']);

    ec_mat = fullfile(temporal_dir, ...
        [ec_file_tag '_' char(temporal_plot_lzc_column) '_temporal_LZc.mat']);

    if ~exist(eo_mat, 'file') || ~exist(ec_mat, 'file')
        fprintf('Missing temporal EO/EC MAT for %s %s %s. Skipping.\n', ...
            char(participant), char(session_name), char(epoch_name));
        continue;
    end

    participant_diff_dir = fullfile(temporal_diff_dir, char(participant));

    if ~exist(participant_diff_dir, 'dir')
        mkdir(participant_diff_dir);
    end

    diff_tag = sprintf('%s_%s_%s_EO_minus_EC_%s', ...
        char(participant), char(session_name), char(epoch_name), char(temporal_plot_lzc_column));

    diff_mat = fullfile(participant_diff_dir, [diff_tag '_temporal_difference.mat']);
    diff_png = fullfile(participant_diff_dir, [diff_tag '_temporal_difference_heatmap.png']);

    if exist(diff_mat, 'file') && exist(diff_png, 'file')
        fprintf('Temporal EO minus EC difference already exists. Skipping:\n%s\n', diff_mat);
    else
        eo_data = load(eo_mat, 'temporal_LZc', 'temporal_times_sec', 'chan_labels');
        ec_data = load(ec_mat, 'temporal_LZc', 'temporal_times_sec', 'chan_labels');

        nCh = min(size(eo_data.temporal_LZc, 1), size(ec_data.temporal_LZc, 1));
        nWin = min(size(eo_data.temporal_LZc, 2), size(ec_data.temporal_LZc, 2));

        temporal_diff = eo_data.temporal_LZc(1:nCh, 1:nWin) - ec_data.temporal_LZc(1:nCh, 1:nWin);
        temporal_times_sec = eo_data.temporal_times_sec(1:nWin);
        chan_labels = eo_data.chan_labels(1:nCh);

        save(diff_mat, ...
            'temporal_diff', ...
            'temporal_times_sec', ...
            'chan_labels', ...
            'participant', ...
            'session_name', ...
            'epoch_name', ...
            'temporal_plot_lzc_column', ...
            'diff_color_limits', ...
            'eo_mat', ...
            'ec_mat', ...
            '-v7.3');

        temporal_lzc_heatmap( ...
            temporal_diff, temporal_times_sec, chan_labels, ...
            [char(participant) ' ' char(session_name) ' ' char(epoch_name) ' Temporal EO - EC LZc'], ...
            diff_png, ...
            diff_color_limits);

        fprintf('Saved temporal EO minus EC difference:\n%s\n', diff_png);
    end

    new_row = table( ...
        participant, ...
        session_name, ...
        epoch_name, ...
        string(diff_mat), ...
        string(diff_png), ...
        'VariableNames', {'Participant','Session','Epoch','Diff_MAT','Diff_PNG'} ...
    );

    temporal_pair_index = [temporal_pair_index; new_row];

end

temporal_pair_index = normalize_lzc_table_ids(temporal_pair_index);

end